name: flutter_nos
description: A Flutter plugin for Netease NOS SDK. (网易数帆对象存储直传 SDK)
version: 0.0.1
repository: https://github.com/aJIEw/flutter_nos

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  plugin:
    platforms:
      android:
        package: com.shimi.flutter_nos
        pluginClass: FlutterNosPlugin
      ios:
        pluginClass: FlutterNosPlugin
